from tkinter import *
import os
import pickle


numCanister = int()
def readCanister():
    fichier = open("data","rb")
    global conf_canister1,conf_canister2,conf_canister3,conf_canister4,conf_canister5,conf_canister6
    conf_canister1 = pickle.load(fichier)
    conf_canister2 = pickle.load(fichier)
    conf_canister3 = pickle.load(fichier)
    conf_canister4 = pickle.load(fichier)
    conf_canister5 = pickle.load(fichier)
    conf_canister6 = pickle.load(fichier)
    fichier.close()
readCanister()
canister = int()
visotube = int()

def modif():
    def save():
        readCanister()
        eval("conf_canister"+str(canister))[str(visotube)]["name"] = name.get()
        eval("conf_canister"+str(canister))[str(visotube)]["stock"] = int(stock.get())
        eval("conf_canister"+str(canister))[str(visotube)]["num"] = num.get()
        eval("conf_canister"+str(canister))[str(visotube)]["lait"] = lait.get()
        eval("conf_canister"+str(canister))[str(visotube)]["TP"] = TP.get()
        eval("conf_canister"+str(canister))[str(visotube)]["TB"] = TB.get()
        eval("conf_canister"+str(canister))[str(visotube)]["impl"] = impl.get()
        eval("conf_canister"+str(canister))[str(visotube)]["long"] = longu.get()
        eval("conf_canister"+str(canister))[str(visotube)]["loco"] = loco.get()
        eval("conf_canister"+str(canister))[str(visotube)]["tempera"] = tempera.get()
        eval("conf_canister"+str(canister))[str(visotube)]["vitess"] = vitess.get()
        eval("conf_canister"+str(canister))[str(visotube)]["color"] = color.get()
        fichier = open("data","wb")
        pickle.dump(conf_canister1,fichier)
        pickle.dump(conf_canister2,fichier)
        pickle.dump(conf_canister3,fichier)
        pickle.dump(conf_canister4,fichier)
        pickle.dump(conf_canister5,fichier)
        pickle.dump(conf_canister6,fichier)
        fichier.close()
        fen2.destroy()
    def aff():
        readCanister()
        name.delete(0,50)
        stock.delete(0,50)
        num.delete(0,50)
        lait.delete(0,50)
        TP.delete(0,50)
        TB.delete(0,50)
        impl.delete(0,50)
        longu.delete(0,50)
        loco.delete(0,50)
        tempera.delete(0,50)
        vitess.delete(0,50)
        color.delete(0,50)
        name.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["name"])
        stock.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["stock"])
        num.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["num"])
        lait.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["lait"])
        TP.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["TP"])
        TB.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["TB"])
        impl.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["impl"])
        longu.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["long"])
        loco.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["loco"])
        tempera.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["tempera"])
        vitess.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["vitess"])
        color.insert(END,eval("conf_canister"+str(canister))[str(visotube)]["color"])
    def clic(event):
        global canister , visotube
        def clic2(event):
            global visotube
            i = listb2.curselection()
            visotube = listb2.get(i)
            aff()

        i = listb.curselection()
        canister = listb.get(i)
        frameListViso = Frame(fen2)
        Label(frameListViso,text="Visotube :").grid(sticky=W)
        scroll2 = Scrollbar(frameListViso)
        listb2 = Listbox(frameListViso,width=25,height=3,activestyle=DOTBOX)
        scroll2.config(command = listb2.yview)
        listb2.config(yscrollcommand = scroll2.set)
        if int(canister)<4:
            for i in "0123456" : listb2.insert(END,i)
            listb2.bind("<ButtonRelease-1>",clic2)
        else :
            for i in ["0","1","2","3","4","5","6","7","8","9","10","11"] : listb2.insert(END,i)
            listb2.bind("<ButtonRelease-1>",clic2)
        listb2.grid(column=0,row=1)
        scroll2.grid(column=1,row=1)
        frameListViso.grid(column=1,row=0,padx=20,pady=20)
    fen2 = Tk()
    fen2.title("Modification")
    frameListCanister = Frame(fen2)
    Label(frameListCanister,text="Canister :").grid(sticky=W)
    scroll = Scrollbar(frameListCanister)
    listb = Listbox(frameListCanister,width=25,height=3,activestyle=DOTBOX)
    scroll.config(command = listb.yview)
    listb.config(yscrollcommand = scroll.set)
    for i in "123456" : listb.insert(END,i)
    listb.grid(column=0,row=1)
    scroll.grid(column=1,row=1)
    frameListCanister.grid(column=0,row=0,padx=20,pady=20)
    listb.bind("<ButtonRelease-1>",clic)

    frame1 =Frame(fen2)
    frame2 =Frame(fen2)
    Label(frame1,text="name :").grid(sticky=W)
    name = Entry(frame1)
    name.grid(sticky=W)
    Label(frame1,text="couleur :").grid(sticky=W)
    color = Entry(frame1)
    color.grid(sticky=W)
    Label(frame1,text="stock :").grid(sticky=W)
    stock = Entry(frame1)
    stock.grid(sticky=W)
    Label(frame1,text="numéro du taureau :").grid(sticky=W)
    num = Entry(frame1)
    num.grid(sticky=W)
    Label(frame1,text="lait :").grid(sticky=W)
    lait = Entry(frame1)
    lait.grid(sticky=W)
    Label(frame1,text="TP :").grid(sticky=W)
    TP = Entry(frame1)
    TP.grid(sticky=W)
    Label(frame2,text="TB :").grid(sticky=W)
    TB = Entry(frame2)
    TB.grid(sticky=W)
    Label(frame2,text="implantation arrière :").grid(sticky=W)
    impl = Entry(frame2)
    impl.grid(sticky=W)
    Label(frame2,text="longueur des Trayons :").grid(sticky=W)
    longu = Entry(frame2)
    longu.grid(sticky=W)
    Label(frame2,text="vitesse de traite :").grid(sticky=W)
    vitess = Entry(frame2)
    vitess.grid(sticky=W)
    Label(frame2,text="tempérament :").grid(sticky=W)
    tempera = Entry(frame2)
    tempera.grid(sticky=W)
    Label(frame2,text="locomotion :").grid(sticky=W)
    loco = Entry(frame2)
    loco.grid(sticky=W)
    frame1.grid(column=0,row=1,padx=20,pady=20)
    frame2.grid(column=1,row=1,padx=20,pady=20)
    Button(fen2,text="Sauvegarder",command=save).grid(column=1,row=2)
    fen2.mainloop()

"""
fen1 = Tk()

Button(fen1,text="modifer",command=modif).pack()

fen1.mainloop()"""